// <auto-generated />
using System;
using Backend.Data.Branch;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.Branch
{
    [DbContext(typeof(BranchDbContext))]
    [Migration("20251217000000_UpdateDeliveryStatusEnum")]
    partial class UpdateDeliveryStatusEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // Model configuration would go here, but for a data-only migration
            // we don't need to rebuild the entire model
#pragma warning restore 612, 618
        }
    }
}
