// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.Branch
{
    [DbContext(typeof(Backend.Data.Branch.BranchDbContext))]
    [Migration("20251214100000_AddDeliveryOrderTable")]
    partial class AddDeliveryOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Backend.Models.Entities.Branch.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        ;

                    b.Property<Guid>("OrderId")
                        ;

                    b.Property<Guid?>("CustomerId")
                        ;

                    b.Property<Guid?>("DriverId")
                        ;

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("DeliveryLocation")
                        ;

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        ;

                    b.Property<DateTime?>("ActualDeliveryTime")
                        ;

                    b.Property<int>("DeliveryStatus")
                        ;

                    b.Property<int>("Priority")
                        ;

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("Priority");

                    b.ToTable("DeliveryOrders");
                });

#pragma warning restore 612, 618
        }
    }
}