// <auto-generated />
using System;
using Backend.Data.Branch;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.Branch
{
    [DbContext(typeof(BranchDbContext))]
    partial class BranchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Backend.Models.Entities.Branch.CashDrawer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal?>("ActualCash")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<Guid>("BranchId")
                        ;

                    b.Property<DateTime?>("ClosedAt")
                        ;

                    b.Property<Guid?>("ClosedBy")
                        ;

                    b.Property<string>("DenominationBreakdown")
                        ;

                    b.Property<decimal>("ExpectedCash")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<DateTime>("OpenedAt")
                        ;

                    b.Property<Guid>("OpenedBy")
                        ;

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<decimal?>("Variance")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("OpenedAt");

                    b.HasIndex("OpenedBy");

                    b.HasIndex("Status");

                    b.ToTable("CashDrawers");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.CashTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<Guid>("CashDrawerId")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CashDrawerId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Type");

                    b.ToTable("CashTransactions");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("DescriptionAr")
                        ;

                    b.Property<string>("DescriptionEn")
                        ;

                    b.Property<int>("DisplayOrder")
                        ;

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<Guid?>("ParentCategoryId")
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AdditionalNumber")
                        .HasMaxLength(10)
                        ;

                    b.Property<string>("AddressAr")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("AddressEn")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(10)
                        ;

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("District")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<DateTime?>("LastVisitAt")
                        ;

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("LoyaltyPoints")
                        ;

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        ;

                    b.Property<string>("StreetName")
                        .HasMaxLength(200)
                        ;

                    b.Property<decimal>("TotalPurchases")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<int>("VisitCount")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("Phone");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime?>("ActualDeliveryTime")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<Guid?>("CustomerId")
                        ;

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("DeliveryLocation")
                        ;

                    b.Property<int>("DeliveryStatus")
                        ;

                    b.Property<Guid?>("DriverId")
                        ;

                    b.Property<int?>("EstimatedDeliveryMinutes")
                        ;

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        ;

                    b.Property<Guid>("OrderId")
                        ;

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("Priority")
                        ;

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("DriverId");

                    b.HasIndex("EstimatedDeliveryTime");

                    b.HasIndex("OrderId");

                    b.HasIndex("Priority");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AddressAr")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("AddressEn")
                        .HasMaxLength(500)
                        ;

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(3, 2)
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<bool>("IsAvailable")
                        ;

                    b.Property<DateTime>("LicenseExpiryDate")
                        ;

                    b.Property<string>("LicenseImagePath")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("TotalDeliveries")
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("VehicleImagePath")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("VehicleType")
                        .HasMaxLength(100)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("LicenseNumber");

                    b.HasIndex("Phone");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<int>("ApprovalStatus")
                        ;

                    b.Property<DateTime?>("ApprovedAt")
                        ;

                    b.Property<Guid?>("ApprovedBy")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<Guid>("ExpenseCategoryId")
                        ;

                    b.Property<DateTime>("ExpenseDate")
                        ;

                    b.Property<int>("PaymentMethod")
                        ;

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("ReceiptImagePath")
                        .HasMaxLength(500)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal?>("BudgetAllocation")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.InvoiceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<int?>("CustomHeight")
                        ;

                    b.Property<int?>("CustomWidth")
                        ;

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<int>("PaperSize")
                        ;

                    b.Property<string>("Schema")
                        .IsRequired()
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("InvoiceTemplates");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PendingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid?>("CustomerId")
                        ;

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        ;

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime>("ExpiresAt")
                        ;

                    b.Property<int?>("GuestCount")
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<int>("OrderType")
                        ;

                    b.Property<DateTime?>("RetrievedAt")
                        ;

                    b.Property<int>("Status")
                        ;

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<Guid?>("TableId")
                        ;

                    b.Property<int?>("TableNumber")
                        ;

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime?>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerName");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderType");

                    b.HasIndex("Status");

                    b.HasIndex("TableNumber");

                    b.ToTable("PendingOrders");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PendingOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<Guid>("PendingOrderId")
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("ProductSku")
                        .HasMaxLength(50)
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("PendingOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("PendingOrderItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PrinterConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("AutoPrint")
                        ;

                    b.Property<Guid>("BranchId")
                        ;

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("FooterLine1")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("FooterLine2")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("FooterLine3")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("HeaderLine1")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("HeaderLine2")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("HeaderLine3")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("PaperWidth")
                        ;

                    b.Property<int?>("Port")
                        ;

                    b.Property<bool>("PrintBarcode")
                        ;

                    b.Property<bool>("PrintLogo")
                        ;

                    b.Property<bool>("PrintQrCode")
                        ;

                    b.Property<string>("PrinterModel")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        ;

                    b.Property<DateTime?>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ConnectionType");

                    b.ToTable("PrinterConfigurations");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid>("CategoryId")
                        ;

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("DescriptionAr")
                        ;

                    b.Property<string>("DescriptionEn")
                        ;

                    b.Property<bool>("HasInventoryDiscrepancy")
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<int>("MinStockThreshold")
                        ;

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<int>("StockLevel")
                        ;

                    b.Property<Guid?>("SupplierId")
                        ;

                    b.Property<Guid?>("UnitId")
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("StockLevel");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("DisplayOrder")
                        ;

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<DateTime>("UploadedAt")
                        ;

                    b.Property<Guid>("UploadedBy")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<decimal>("DiscountAmount")
                        ;

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<decimal>("DiscountValue")
                        ;

                    b.Property<decimal>("GrandTotal")
                        ;

                    b.Property<string>("InvoiceImagePath")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Notes")
                        ;

                    b.Property<int>("PaymentStatus")
                        ;

                    b.Property<DateTime>("PurchaseDate")
                        ;

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime?>("ReceivedDate")
                        ;

                    b.Property<decimal>("Subtotal")
                        ;

                    b.Property<Guid>("SupplierId")
                        ;

                    b.Property<decimal>("TaxAmount")
                        ;

                    b.Property<bool>("TaxIncluded")
                        ;

                    b.Property<decimal>("TaxRate")
                        ;

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("PurchaseOrderNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PurchaseLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<Guid>("PurchaseId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseLineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Return", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime?>("ApprovedAt")
                        ;

                    b.Property<Guid?>("ApprovedBy")
                        ;

                    b.Property<Guid>("BranchId")
                        ;

                    b.Property<DateTime?>("CompletedAt")
                        ;

                    b.Property<Guid?>("CustomerId")
                        ;

                    b.Property<Guid?>("ExchangeSaleId")
                        ;

                    b.Property<bool>("IsExchange")
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        ;

                    b.Property<Guid>("OriginalSaleId")
                        ;

                    b.Property<Guid>("ProcessedBy")
                        ;

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("RefundMethod")
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("RefundReference")
                        .HasMaxLength(100)
                        ;

                    b.Property<decimal>("RestockingFee")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime>("ReturnDate")
                        ;

                    b.Property<Guid?>("ReturnPolicyId")
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExchangeSaleId");

                    b.HasIndex("OriginalSaleId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("ReturnDate");

                    b.HasIndex("ReturnPolicyId");

                    b.HasIndex("Status");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ReturnLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<bool>("Restocked")
                        ;

                    b.Property<DateTime?>("RestockedAt")
                        ;

                    b.Property<Guid>("ReturnId")
                        ;

                    b.Property<Guid>("SaleLineItemId")
                        ;

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReturnId");

                    b.HasIndex("SaleLineItemId");

                    b.ToTable("ReturnLineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ReturnPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AllowedConditions")
                        .IsRequired()
                        ;

                    b.Property<Guid>("BranchId")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid?>("CreatedBy")
                        ;

                    b.Property<bool>("ExchangeAllowed")
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<int>("MaxReturnDays")
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("RefundMethods")
                        .IsRequired()
                        ;

                    b.Property<bool>("RequireManagerApproval")
                        ;

                    b.Property<bool>("RequireReceipt")
                        ;

                    b.Property<decimal>("RestockingFeePercent")
                        .HasPrecision(5, 2)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<Guid?>("UpdatedBy")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.ToTable("ReturnPolicies");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal?>("AmountPaid")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<Guid>("CashierId")
                        ;

                    b.Property<decimal?>("ChangeReturned")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime?>("CompletedAt")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid?>("CustomerId")
                        ;

                    b.Property<int?>("GuestCount")
                        ;

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        ;

                    b.Property<int>("InvoiceType")
                        ;

                    b.Property<bool>("IsReturn")
                        ;

                    b.Property<bool>("IsVoided")
                        ;

                    b.Property<string>("Notes")
                        ;

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        ;

                    b.Property<int?>("OrderType")
                        ;

                    b.Property<Guid?>("OriginalSaleId")
                        ;

                    b.Property<int>("PaymentMethod")
                        ;

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        ;

                    b.Property<Guid?>("ReturnApprovedBy")
                        ;

                    b.Property<DateTime?>("ReturnDate")
                        ;

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(100)
                        ;

                    b.Property<DateTime>("SaleDate")
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<int?>("TableId")
                        ;

                    b.Property<int?>("TableNumber")
                        ;

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("TotalDiscount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<Guid?>("UserId")
                        ;

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        ;

                    b.Property<DateTime?>("VoidedAt")
                        ;

                    b.Property<Guid?>("VoidedBy")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("IsReturn");

                    b.HasIndex("IsVoided");

                    b.HasIndex("OrderType");

                    b.HasIndex("OriginalSaleId");

                    b.HasIndex("ReturnDate");

                    b.HasIndex("SaleDate");

                    b.HasIndex("Status");

                    b.HasIndex("TableId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.SaleLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("DiscountType")
                        ;

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<decimal>("DiscountedUnitPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("ItemStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<int>("ReturnQuantity")
                        ;

                    b.Property<Guid>("SaleId")
                        ;

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        ;

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ItemStatus");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("PaymentMethod")
                        ;

                    b.Property<DateTime>("ProcessedAt")
                        ;

                    b.Property<Guid>("ProcessedBy")
                        ;

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid>("SaleId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<Guid>("UpdatedBy")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AddressAr")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("AddressEn")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("DeliveryTerms")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.SyncQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("ErrorMessage")
                        ;

                    b.Property<DateTime?>("LastSyncAttempt")
                        ;

                    b.Property<int>("RetryCount")
                        ;

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("SyncStatus")
                        ;

                    b.Property<DateTime>("Timestamp")
                        ;

                    b.Property<string>("TransactionData")
                        .IsRequired()
                        ;

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Timestamp");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("Capacity")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int?>("CurrentGuestCount")
                        ;

                    b.Property<Guid?>("CurrentSaleId")
                        ;

                    b.Property<DateTime?>("DeletedAt")
                        ;

                    b.Property<decimal>("Height")
                        .HasPrecision(5, 2)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("Number")
                        ;

                    b.Property<DateTime?>("OccupiedAt")
                        ;

                    b.Property<decimal>("PositionX")
                        .HasPrecision(5, 2)
                        ;

                    b.Property<decimal>("PositionY")
                        .HasPrecision(5, 2)
                        ;

                    b.Property<int>("Rotation")
                        ;

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<decimal>("Width")
                        .HasPrecision(5, 2)
                        ;

                    b.Property<int?>("ZoneId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("AllowFractional")
                        ;

                    b.Property<Guid?>("BaseUnitId")
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(18, 6)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<int>("DecimalPlaces")
                        ;

                    b.Property<int>("DisplayOrder")
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<bool>("IsBaseUnit")
                        ;

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CreatedBy")
                        ;

                    b.Property<string>("Email")
                        .IsRequired()
                        ;

                    b.Property<string>("FullNameAr")
                        ;

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<DateTime?>("LastActivityAt")
                        ;

                    b.Property<DateTime?>("LastLoginAt")
                        ;

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        ;

                    b.Property<string>("Phone")
                        ;

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        ;

                    b.Property<string>("Role")
                        .IsRequired()
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<string>("Username")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastLoginAt");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        ;

                    b.Property<int>("DisplayOrder")
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.CashDrawer", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Entities.Branch.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByUser");

                    b.Navigation("OpenedByUser");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.CashTransaction", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.CashDrawer", "CashDrawer")
                        .WithMany("Transactions")
                        .HasForeignKey("CashDrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashDrawer");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Category", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.DeliveryOrder", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Customer", "Customer")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Driver", "Driver")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "Sale")
                        .WithOne("DeliveryOrder")
                        .HasForeignKey("Backend.Models.Entities.Branch.DeliveryOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Expense", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PendingOrderItem", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.PendingOrder", "PendingOrder")
                        .WithMany("Items")
                        .HasForeignKey("PendingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingOrder");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Product", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ProductImage", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Purchase", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PurchaseLineItem", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Product", "Product")
                        .WithMany("PurchaseLineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.Purchase", "Purchase")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Return", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Entities.Branch.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "ExchangeSale")
                        .WithMany()
                        .HasForeignKey("ExchangeSaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "OriginalSale")
                        .WithMany()
                        .HasForeignKey("OriginalSaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.ReturnPolicy", "ReturnPolicy")
                        .WithMany()
                        .HasForeignKey("ReturnPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Customer");

                    b.Navigation("ExchangeSale");

                    b.Navigation("OriginalSale");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("ReturnPolicy");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ReturnLineItem", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.Return", "Return")
                        .WithMany("LineItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.SaleLineItem", "SaleLineItem")
                        .WithMany()
                        .HasForeignKey("SaleLineItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Return");

                    b.Navigation("SaleLineItem");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Sale", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "OriginalSale")
                        .WithMany("ReturnedSales")
                        .HasForeignKey("OriginalSaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Backend.Models.Entities.Branch.Table", "Table")
                        .WithMany("Sales")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Entities.Branch.User", null)
                        .WithMany("Sales")
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("OriginalSale");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.SaleLineItem", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Product", "Product")
                        .WithMany("SaleLineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "Sale")
                        .WithMany("LineItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.SalePayment", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Branch.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Table", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Zone", "Zone")
                        .WithMany("Tables")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Unit", b =>
                {
                    b.HasOne("Backend.Models.Entities.Branch.Unit", "BaseUnit")
                        .WithMany("DerivedUnits")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.CashDrawer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Customer", b =>
                {
                    b.Navigation("DeliveryOrders");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Driver", b =>
                {
                    b.Navigation("DeliveryOrders");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.PendingOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PurchaseLineItems");

                    b.Navigation("SaleLineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Purchase", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Return", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Sale", b =>
                {
                    b.Navigation("DeliveryOrder");

                    b.Navigation("LineItems");

                    b.Navigation("Payments");

                    b.Navigation("ReturnedSales");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Table", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Unit", b =>
                {
                    b.Navigation("DerivedUnits");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.User", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Backend.Models.Entities.Branch.Zone", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
